CREATE TABLE customers (Customer_ID INT AUTO_INCREMENT PRIMARY KEY,C_Name VARCHAR(100),City VARCHAR(100));

CREATE TABLE products (Product_ID INT AUTO_INCREMENT PRIMARY KEY,P_Name VARCHAR(100),Category VARCHAR(100),Price DECIMAL(10,2));

CREATE TABLE orders (Order_ID INT AUTO_INCREMENT PRIMARY KEY,Customer_ID INT,Order_Date DATE,FOREIGN KEY (Customer_ID) REFERENCES customers(Customer_ID));

CREATE TABLE order_Items (Order_Item_ID INT AUTO_INCREMENT PRIMARY KEY, Order_ID INT,Product_ID INT,Quantity INT,FOREIGN KEY (Order_ID) REFERENCES orders(Order_ID),FOREIGN KEY (Product_ID) REFERENCES products(Product_ID));